### ISSUE TITLE
Can You Add New Windows Versions to Your Project?

### ISSUE THREAD

**Issue by furkankadirguzeloglu** [VergiliusProject/vergilius-project#14]
**Hi, Can you add new windows versions please?**

- Windows 10 21H2 (19044.x)
- Windows 11 21H2 (22000.376)

Thank you in advance for your interest. - Furkan Kadir Güzeloğlu

**Comment by SergiusTheBest** [comment]
Yes, I will add them soon. Stay tuned!

**Comment by SergiusTheBest** [comment]
@furkankadirguzeloglu Windows 10 21H2 (19044.x) is added. However note that Microsoft made a mess with version numbers. We take the version from file resources and there is 10.0.19041.1288 instead of 10.0.19044.1288. I'm not sure why they did it in that way. All Windows files are marked as 19041 and not 19042-19044.

As for the Windows 11 21H2 (22000.376): There is Windows 11 21H2 (10.0.22000.194) that is an RTM build. 22000.376 is just a small update.

**Comment by furkankadirguzeloglu** [comment]
> @furkankadirguzeloglu Windows 10 21H2 (19044.x) is added. However note that Microsoft made a mess with version numbers. We take the version from file resources and there is 10.0.19041.1288 instead of 10.0.19044.1288. I'm not sure why they did it in that way. All Windows files are marked as 19041 and not 19042-19044.
> 
> As for the Windows 11 21H2 (22000.376): There is Windows 11 21H2 (10.0.22000.194) that is an RTM build. 22000.376 is just a small update.

Thx.
